/**
 * Skills data loader and helpers.
 *
 * Phase 03.1.1 T5: sources skills from `data/skills.ndjson` via the chunked
 * streaming loader (V8-string-limit safe at 50k+ records). The pre-T5
 * `F1_STREAMING_LOADER=1` flag is gone; the production code path that T2's
 * smoke proved IS the default now. The legacy `data/skills.json` import
 * branch is removed.
 *
 * In CI: `resolveSkillsNdjsonPath()` requires `data/skills.ndjson` to be on
 * disk (restored from cache, downloaded from `skills-latest` release asset,
 * or generated by filter.js earlier in the workflow). Throws if missing.
 *
 * Local dev: prefers `data/skills.ndjson`; falls back to legacy `skills.json`
 * with a loud warning during the transition window. Drop the legacy branch
 * in a post-T5 cleanup commit one week after main stabilizes.
 */

import { readFileSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

import pipelineStats from '../../data/pipeline-stats.json';
import { loadAllSkillsMemo } from '../../scripts/lib/skills-stream.js';
import { resolveSkillsNdjsonPath } from '../../scripts/lib/build-input.js';

// T5: streaming NDJSON load is the default. loadAllSkillsMemo caches per-path
// so Astro getStaticPaths() callsites don't re-parse the file 1000x at build.
const skillsData = loadAllSkillsMemo(resolveSkillsNdjsonPath());

// Similar skills are pre-computed at build time by scripts/compute-similar.js.
// We use readFileSync instead of import because the file may not exist on the
// very first build (before compute-similar.js has ever run). Import would make
// the entire build fail; readFileSync lets us degrade gracefully.
const __skills_dirname = dirname(fileURLToPath(import.meta.url));
const __similar_path = join(__skills_dirname, '../../data/similar-skills.json');
let similarSkillsData = { similar: {} };
if (existsSync(__similar_path)) {
  try {
    similarSkillsData = JSON.parse(readFileSync(__similar_path, 'utf-8'));
  } catch {
    // Malformed file — degrade gracefully
  }
}

// API graph (services ↔ skills mapping)
const __api_graph_path = join(__skills_dirname, '../../data/api-graph.json');
let apiGraphData = { services: {}, skill_integrations: {} };
if (existsSync(__api_graph_path)) {
  try {
    apiGraphData = JSON.parse(readFileSync(__api_graph_path, 'utf-8'));
  } catch {
    // Degrade gracefully
  }
}

/** @type {import('./types').Skill[]} */
export const allSkills = skillsData;

/**
 * Phase 3.1: filter out records flagged as duplicates by scripts/enrich.js.
 * Used by default browse helpers below. Direct-URL access
 * (getSkillBySlug) intentionally does NOT call this — a user landing on
 * a duplicate's permalink still sees the page (with a "copy of X" banner
 * rendered by the detail template, when 3.4 adds it).
 *
 * is_duplicate has three states:
 *   - true:  hide from default browse
 *   - false: assessed and clean → show
 *   - null:  not yet assessed (no vector) → show (default-permissive)
 */
function notDuplicate(s) {
  return s.is_duplicate !== true;
}

export function getFeaturedSkills(limit = 6) {
  return allSkills
    .filter(notDuplicate)
    .filter(s => s.quality_tier === 'featured')
    .slice(0, limit);
}

export function getSkillsByCategory(category) {
  return allSkills
    .filter(notDuplicate)
    .filter(s => s.category === category)
    .sort((a, b) => b.quality_score - a.quality_score);
}

export function getSkillBySlug(slug) {
  // Phase 3.1: NO notDuplicate filter here — direct-URL access must still
  // resolve to a duplicate's page (detail template can render a "copy of X"
  // banner). Only default browse hides duplicates.
  return allSkills.find(s => s.slug === slug) || null;
}

export function getAllCategories() {
  const cats = {};
  for (const skill of allSkills) {
    if (!notDuplicate(skill)) continue;
    cats[skill.category] = (cats[skill.category] || 0) + 1;
  }
  return Object.entries(cats)
    .map(([name, count]) => ({ name, count, slug: getCategorySlug(name) }))
    .sort((a, b) => b.count - a.count);
}

export function getCategorySlug(category) {
  return category
    .toLowerCase()
    .replace(/[&]/g, 'and')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}

export function getCategoryFromSlug(slug) {
  const cats = getAllCategories();
  return cats.find(c => c.slug === slug)?.name || null;
}

export function getStats() {
  return {
    total: allSkills.length,
    featured: allSkills.filter(s => s.quality_tier === 'featured').length,
    solid: allSkills.filter(s => s.quality_tier === 'solid').length,
    listed: allSkills.filter(s => s.quality_tier === 'listed').length,
    categories: getAllCategories().length,
  };
}

/**
 * Pipeline-wide stats. Always prefers pipeline-stats.json for `total_discovered`
 * (the true scraped count, not just what survived filtering) and uses the
 * current catalog for indexed/featured counts so numbers stay consistent with
 * what's actually rendered.
 */
export function getPipelineStats() {
  return {
    total_discovered: pipelineStats.total_discovered || allSkills.length,
    total_indexed: allSkills.length,
    total_featured: allSkills.filter(s => s.quality_tier === 'featured').length,
    updated_at: pipelineStats.timestamp || null,
  };
}

// --- Creator aggregation helpers (Phase 4) ---

const MS_PER_DAY = 24 * 60 * 60 * 1000;

/**
 * Build a Map of creator records from `allSkills`. A creator = the `owner`
 * segment of `repo_full_name`. Each record has aggregate stats, badge flags,
 * and their sorted skill list.
 *
 * Bios use the top-scored skill's `repo_description` as a fallback — real
 * GitHub user bios require a user API fetch which is deferred to Phase 2.5.
 */
export function getCreators() {
  const map = new Map();

  for (const skill of allSkills) {
    const username = (skill.repo_full_name || '').split('/')[0];
    if (!username) continue;

    let rec = map.get(username);
    if (!rec) {
      rec = {
        username,
        avatar_url: skill.repo_owner_avatar || null,
        type: skill.repo_owner_type || 'User',
        bio_fallback: null,
        skills: [],
        total_skills: 0,
        total_stars: 0,
        // Track which repos we've already counted stars for, so creators
        // with multiple skills in the same repo don't get double-counted
        // (GitHub stars are repo-level, not skill-level).
        _counted_repos: new Set(),
        avg_quality_score: 0,
        avg_quality_score_precise: 0,
        tier_counts: { featured: 0, solid: 0, listed: 0 },
        categories: new Set(),
        first_commit_at: null,
        rising_since: null, // earliest first_commit_at among Featured skills
        isProlific: false,
        isQuality: false,
        isRising: false,
      };
      map.set(username, rec);
    }

    rec.skills.push(skill);
    // Dedupe stars at the repo level — one repo's star count is one contribution
    if (skill.repo_full_name && !rec._counted_repos.has(skill.repo_full_name)) {
      rec._counted_repos.add(skill.repo_full_name);
      rec.total_stars += skill.repo_stars || 0;
    }
    rec.tier_counts[skill.quality_tier] = (rec.tier_counts[skill.quality_tier] || 0) + 1;
    if (skill.category) rec.categories.add(skill.category);

    const commitAt = skill.skill_first_commit_at || skill.repo_created_at || null;
    if (commitAt) {
      if (!rec.first_commit_at || new Date(commitAt) < new Date(rec.first_commit_at)) {
        rec.first_commit_at = commitAt;
      }
      if (skill.quality_tier === 'featured') {
        if (!rec.rising_since || new Date(commitAt) > new Date(rec.rising_since)) {
          rec.rising_since = commitAt;
        }
      }
    }
  }

  const now = Date.now();

  for (const rec of map.values()) {
    rec.skills.sort((a, b) => (b.quality_score || 0) - (a.quality_score || 0));
    rec.total_skills = rec.skills.length;
    const sumScores = rec.skills.reduce((a, b) => a + (b.quality_score || 0), 0);
    // Total quality = composite score rewarding both breadth and depth.
    // 4 skills at 95 each (380) beats 2 skills at 99 each (198) — the right
    // answer, because sustained multi-skill quality is a stronger signal
    // than getting lucky with two high-scoring skills.
    rec.total_quality_score = sumScores;
    // Average is retained for the profile page header display
    rec.avg_quality_score_precise = rec.total_skills > 0 ? sumScores / rec.total_skills : 0;
    rec.avg_quality_score = Math.round(rec.avg_quality_score_precise);

    // Strip the temporary _counted_repos helper before exposing the record
    delete rec._counted_repos;

    // Fallback bio from the top-scored skill's repo_description
    const top = rec.skills[0];
    rec.bio_fallback = top?.repo_description || null;

    // Convert categories Set → sorted array for template iteration
    rec.categories = [...rec.categories].sort();

    // Badges
    rec.isProlific = rec.total_skills >= 5;
    rec.isQuality = rec.total_skills >= 2 && rec.tier_counts.featured === rec.total_skills;
    if (rec.rising_since) {
      const age = (now - Date.parse(rec.rising_since)) / MS_PER_DAY;
      rec.isRising = age >= 0 && age <= 30;
    }
  }

  return map;
}

export function getCreatorByUsername(username) {
  if (!username) return null;
  const creators = getCreators();
  return creators.get(username) || null;
}

/**
 * Leaderboards for /creators index. Returns an object with four top-10
 * arrays. Each element is a creator record from getCreators().
 */
export function getCreatorLeaderboards(topN = 10) {
  const creators = [...getCreators().values()];

  const byFeatured = [...creators]
    .filter(c => c.tier_counts.featured > 0)
    .sort((a, b) => (b.tier_counts.featured - a.tier_counts.featured) || (b.avg_quality_score - a.avg_quality_score))
    .slice(0, topN);

  const prolific = [...creators]
    .sort((a, b) => (b.total_skills - a.total_skills) || (b.avg_quality_score - a.avg_quality_score))
    .slice(0, topN);

  // Total Quality — composite score across all indexed skills.
  // Rewards both breadth (more skills) and depth (higher avg) — the right
  // answer when the catalog has a ceiling of 99 and lots of 2-skill creators
  // tied at the top. `microsoft` with 8 skills at 92 (total 739) beats
  // `affaan-m` with 2 skills at 99 (total 198), which matches intuition.
  const quality = [...creators]
    .filter(c => c.total_skills >= 2)
    .sort((a, b) =>
      (b.total_quality_score - a.total_quality_score)
      || (b.total_skills - a.total_skills)
      || (b.total_stars - a.total_stars)
    )
    .slice(0, topN);

  const rising = [...creators]
    .filter(c => c.rising_since)
    .sort((a, b) => new Date(b.rising_since).getTime() - new Date(a.rising_since).getTime())
    .slice(0, topN);

  return { byFeatured, prolific, quality, rising };
}

/**
 * Browse-page-friendly view of every creator. Omits heavy fields (the
 * `skills` array) and keeps only what the browse table displays or filters
 * on. Returned as a plain array sorted by total_quality_score desc
 * (the default sort for /creators/all/).
 */
export function getCreatorsForBrowse() {
  const creators = [...getCreators().values()];
  return creators
    .map(c => ({
      username: c.username,
      avatar_url: c.avatar_url,
      type: c.type,
      total_skills: c.total_skills,
      featured_count: c.tier_counts?.featured || 0,
      total_stars: c.total_stars,
      total_quality_score: c.total_quality_score,
      avg_quality_score_precise: c.avg_quality_score_precise,
      first_commit_at: c.first_commit_at,
      categories: Array.isArray(c.categories) ? c.categories : [...(c.categories || [])],
    }))
    .sort((a, b) => (b.total_quality_score - a.total_quality_score) || (b.total_skills - a.total_skills));
}

export function getRelatedSkills(skill, limit = 4) {
  return allSkills
    .filter(notDuplicate)
    .filter(s => s.category === skill.category && s.id !== skill.id)
    .sort((a, b) => b.quality_score - a.quality_score)
    .slice(0, limit);
}

/**
 * Returns the full API graph data for use by /apis/ pages.
 * Loaded once at build time via readFileSync in this module (not in .astro
 * files, where import.meta.url resolves to a Vite virtual module path).
 */
export function getApiGraph() {
  return apiGraphData;
}

/**
 * Returns all detected services sorted by skill count descending.
 */
export function getAllServices() {
  const services = Object.values(apiGraphData.services || {});
  return services.sort((a, b) => (b.skill_count || 0) - (a.skill_count || 0));
}

/**
 * Returns a single service by ID, or null if not found.
 */
export function getServiceById(serviceId) {
  return apiGraphData.services?.[serviceId] || null;
}

/**
 * Returns the list of API/service integrations for a given skill,
 * enriched with service metadata (name, category, url). The data comes
 * from the pre-computed api-graph.json produced by scripts/mine-apis.js.
 */
export function getSkillIntegrations(skill) {
  if (!skill || !skill.slug) return [];
  const integrationIds = apiGraphData?.skill_integrations?.[skill.slug] || [];
  return integrationIds.map(id => {
    const svc = apiGraphData.services?.[id];
    return svc ? { id, name: svc.name, category: svc.category, url: svc.url } : null;
  }).filter(Boolean);
}

/**
 * Semantically similar skills for a given skill, pre-computed from the
 * vector embeddings by scripts/compute-similar.js. Returns an array of
 * {slug, score, name, category, quality_tier} objects, or an empty array
 * if similar-skills.json hasn't been generated yet.
 *
 * These are different from getRelatedSkills() which just filters by
 * same-category. getSimilarSkills() uses cosine similarity over the
 * full skill content embedding — it finds skills that are semantically
 * about the same thing, regardless of which category they're in.
 */
export function getSimilarSkills(skill, limit = 5) {
  if (!skill || !skill.slug) return [];
  const map = similarSkillsData?.similar || {};
  const entries = map[skill.slug];
  if (!Array.isArray(entries)) return [];
  // Enrich with full skill records so the template can use SkillCard
  return entries.slice(0, limit).map(entry => {
    const fullSkill = allSkills.find(s => s.slug === entry.slug);
    return fullSkill ? { ...fullSkill, similarity_score: entry.score } : null;
  }).filter(Boolean);
}

export function timeAgo(dateStr) {
  if (!dateStr) return 'unknown';
  const now = Date.now();
  const then = new Date(dateStr).getTime();
  const diffMs = now - then;
  const diffDays = Math.floor(diffMs / (1000 * 60 * 60 * 24));

  if (diffDays === 0) return 'today';
  if (diffDays === 1) return 'yesterday';
  if (diffDays < 7) return `${diffDays} days ago`;
  if (diffDays < 30) return `${Math.floor(diffDays / 7)} weeks ago`;
  if (diffDays < 365) return `${Math.floor(diffDays / 30)} months ago`;
  return `${Math.floor(diffDays / 365)} years ago`;
}

export function tierColor(tier) {
  switch (tier) {
    case 'featured': return { bg: 'bg-amber-100', text: 'text-amber-800', border: 'border-amber-300', dot: 'bg-amber-500' };
    case 'solid': return { bg: 'bg-emerald-100', text: 'text-emerald-800', border: 'border-emerald-300', dot: 'bg-emerald-500' };
    default: return { bg: 'bg-gray-100', text: 'text-gray-600', border: 'border-gray-300', dot: 'bg-gray-400' };
  }
}

export function categoryColor(category) {
  const colors = {
    'Code & Development': 'bg-blue-100 text-blue-800',
    'Web & Frontend': 'bg-purple-100 text-purple-800',
    'Testing & QA': 'bg-green-100 text-green-800',
    'Data & Documents': 'bg-orange-100 text-orange-800',
    'DevOps & Infrastructure': 'bg-red-100 text-red-800',
    'API & Backend': 'bg-indigo-100 text-indigo-800',
    'AI & Automation': 'bg-pink-100 text-pink-800',
    'Productivity & Other': 'bg-gray-100 text-gray-700',
  };
  return colors[category] || 'bg-gray-100 text-gray-700';
}
